background: "1a1b26"
foreground: "a9b1d6"
cursor:     "c0caf5"

b_black:    "444b6a"
b_red:      "ff7a93"
b_green:    "b9f27c"
b_yellow:   "ff9e64"
b_blue:     "7da6ff"
b_magenta:  "bb9af7"
b_cyan:     "0db9d7"
b_white:    "acb0d0"

l_black:    "32344a"
l_red:      "f7768e"
l_green:    "9ece6a"
l_yellow:   "e0af68"
l_blue:     "7aa2f7"
l_magenta:  "ad8ee6"
l_cyan:     "449dab"
l_white:    "787c99"

