[colors.primary]
background          = "#33292b"
foreground          = "#feedf3"

[colors.normal]
black   = "#feedf3"
red     = "#f8e2e7"
green   = "#e0ccd1"
yellow  = "#755f64"
blue    = "#665055"
magenta = "#564448"
cyan    = "#42383a"
white   = "#33292b"

[colors.bright]
black   = "#df2d52"
red     = "#f6661e"
green   = "#c29461"
yellow  = "#2e916d"
blue    = "#1d8991"
magenta = "#006e93"
cyan    = "#5e2180"
white   = "#ba0d35"

