background: ""
foreground: ""
cursor:     ""

b_black:    ""
b_red:      ""
b_green:    ""
b_yellow:   ""
b_blue:     ""
b_magenta:  ""
b_cyan:     ""
b_white:    ""

l_black:    ""
l_red:      ""
l_green:    ""
l_yellow:   ""
l_blue:     ""
l_magenta:  ""
l_cyan:     ""
l_white:    ""