[colors.primary]
foreground  =       "#a5979a"
background  =       "#242323"

[colors.cursor]
cursor      =       "#e24f32"

[colors.normal]
black       =       "#242323"
red         =       "#956f76"
green       =       "#ffa28f"
yellow      =       "#ffc8bd"
blue        =       "#a7868b"
magenta     =       "#f77c64"
cyan        =       "#b89da2"
white       =       "#a5979a"

[colors.bright]
black       =       "#666666"
red         =       "#ff3334"
green       =       "#9ec400"
yellow      =       "#e7c547"
blue        =       "#7aa6da"
magenta     =       "#b77ee0"
cyan        =       "#54ced6"
white       =       "#ffffff"

