
[colors.primary]
foreground  =       "#cc8c33"
background  =       "#fbfaf9"
#cursor      =       "#cc8c33"

[colors.normal]
black       =       "#222022"
red         =       "#8f6c93"
green       =       "#d9b98c"
yellow      =       "#ffd599"
blue        =       "#9a819c"
magenta     =       "#c38022"
cyan        =       "#cb79d2"
white       =       "#9e999f"

[colors.bright]
black       =       "#666666"
red         =       "#ff3334"
green       =       "#9ec400"
yellow      =       "#e7c547"
blue        =       "#7aa6da"
magenta     =       "#b77ee0"
cyan        =       "#54ced6"
white       =       "#ffffff"

