[colors.primary]
foreground          = "#e0def4"
background          = "#191724"

[colors.normal]
black   = "#191724"
red     = "#1f1d2e"
green   = "#26233a"
yellow  = "#6e6a86"
blue    = "#908caa"
magenta = "#e0def4"
cyan    = "#e0def4"
white   = "#524f67"

[colors.bright]
black   = "#eb6f92"
red     = "#f6c177"
green   = "#ebbcba"
yellow  = "#31748f"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#f6c177"
white   = "#524f67"

