[colors.primary]
foreground  =       "#ffad5c"
background  =       "#fbfaf9"

[colors.cursor]
cursor      =       "#ffad5c"

[colors.normal]
black       =       "#2a2734"
red         =       "#8a75f5"
green       =       "#ffb870"
yellow      =       "#ffcc99"
blue        =       "#9a86fd"
magenta     =       "#ffa142"
cyan        =       "#afa0fe"
white       =       "#a4a1b5"

[colors.bright]
black       =       "#666666"
red         =       "#ff3334"
green       =       "#9ec400"
yellow      =       "#e7c547"
blue        =       "#7aa6da"
magenta     =       "#b77ee0"
cyan        =       "#54ced6"
white       =       "#ffffff"

