
[colors.primary]
foreground  =       "#9992b0"
background  =       "#201d2a"
#cursor      =       "#b042ff"

[colors.normal]
black       =       "#201d2a"
red         =       "#9375f5"
green       =       "#dba8ff"
yellow      =       "#ecd1ff"
blue        =       "#a286fd"
magenta     =       "#ca80ff"
cyan        =       "#b5a0fe"
white       =       "#9992b0"

[colors.bright]
black       =       "#666666"
red         =       "#ff3334"
green       =       "#9ec400"
yellow      =       "#e7c547"
blue        =       "#7aa6da"
magenta     =       "#b77ee0"
cyan        =       "#54ced6"
white       =       "#ffffff"

